name: Compilar Dylib para iOS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Descargar Código
      uses: actions/checkout@v4

    - name: Compilar dylib
      run: |
       xcrun --sdk iphoneos clang -dynamiclib -framework UIKit -framework Foundation -framework CoreGraphics -arch arm64 -fobjc-arc Lock.m -o Lock.dylib -miphoneos-version-min=12.0

    - name: Subir archivo terminado
      uses: actions/upload-artifact@v4
      with:
        name: Lock-Dylib
        path: Lock.dylib
